apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseStrategy
metadata:
  name: e2e-fbc-stage-index-strategy
  namespace: managed-release-team-tenant
spec:
  params:
    - name: fromIndex
      value: 'registry-proxy.engineering.redhat.com/rh-osbs/iib-pub-pending:v4.13'
    - name: targetIndex
      value: ''
    - name: binaryImage
      value: 'registry.redhat.io/openshift4/ose-operator-registry:v4.12'
    - name: requestUpdateTimeout
      value: '1000'
    - name: buildTimeoutSeconds
      value: '1000'
  pipelineRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/fbc-release/fbc-release.yaml
  policy: e2e-fbc-stage-index-policy
  serviceAccount: release-service-account
